development:
  session:
    cookie: session_user
    salt: your-secret-salt

  email-confirmation:
    http_prefix: http://localhost:8080
    salt: your-secret-key
    sender: administrator-account@gmail.com
    subject: Register confirmation for development
    body: |
      Please click below
      %s
      
      The example.com Team


production:
  session:
    cookie: session_user
    salt: your-secret-salt
  
  email-confirmation:
    http_prefix: http://your-application-id.appspot.com
    salt: your-secret-salt
    sender: administrator-account@gmail.com
    subject: Register confirmation
    body: |
      Please click below
      %s
      
      The example.com Team
